# For God so loved the world, that He gave His only begotten Son, that all who believe in Him should not perish but have everlasting life.
[package]
name = "worship_coordinator_chirho"
version = "0.1.0"
edition = "2021"


# create loging_chirho feature
[features]
logging_chirho = []


[dependencies]
axum = { version = "0.8.4", features = ["macros", "ws", "multipart"] }
axum-embed = { version = "0.1.0" }
axum-extra = { version = "0.10.1", features = ["cookie"] }
axum-server = { version = "~0.7.0", features = ["tls-rustls"] }
tokio = { version = "1.44.2", features = ["full"] }
serde = { version = "~1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "~0.8", features = ["runtime-tokio-rustls", "mysql", "chrono", "uuid"] }
chrono = { version = "~0.4", features = ["serde"] }
chrono-tz  = { version = "~0.10" }
uuid = { version = "~1.16", features = ["v4", "serde"] }
tower-http = { version = "~0.6", features = ["cors"] }
tower = "~0.5"
tracing = "~0.1"
tracing-subscriber = { version = "~0.3", features = ["env-filter"] }
bcrypt = "~0.17"
jsonwebtoken = "~9.3"

rand = "~0.9"
rust-embed  = { version = "~8.7.0"}

# async-trait = "~0.1"
thiserror = "~2.0"

dotenv = "~0.15"
rustls = "0.23.26"
